server:
  port: 8080

spring:
  application:
    name: receitas-api

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        format_sql: false
    show-sql: true

  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:${DB_PORT:5432}/${POSTGRES_DB:receitas-api_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  flyway:
    enabled: true

security:
  jwt:
    secret-key: b52eec8c75181513637d7b83783bf6ebf300cf5581c97a7b2979ba2410537e1f
    expiration-time: 3600000

logging:
  pattern:
    console: "[%-5level] [${${spring:spring.application.name}}] [%t] [%date{ISO8601}] [%c{1}:%M:%L] [%X{traceId},%X{spanId}] %msg %n"
  level:
    root: INFO